## numpy介绍
NumPy（Numerical Python）是 Python 科学计算的核心库，提供了：
- 高性能的多维数组对象
- 用于数组操作的函数
- 线性代数、傅里叶变换、随机数生成等功能
- 与 C/C++/Fortran 代码集成的工具
## nbarray 核心知识点
- 同构数据容器：所有元素必须是相同类型,不同类型的数据会被强制转换成相同的类型
- 内存连续存储：访问速度远快于Python列表
- 固定大小：创建后不能像列表一样随意扩展
### 广播机制的关键规则
规则1：如果数组维度不同，在形状前面补1
规则2：维度大小为1的轴会被"拉伸"
规则3：不满足条件会抛出异常

### 矢量化思想


In [3]:
# 避免使用循环
# ❌ 不推荐
result = []
for i in range(len(result)):
    result.append(result[i] * 2)
    
# ✅ 推荐使用
result = result * 2

In [2]:
import numpy as np

In [13]:
arr = np.array(1)
print(arr)
print('arr的维度',arr.ndim)
print('arr的形状',arr.shape)

1
arr的维度 0
arr的形状 ()


### 创建数组的多种方式
- 基础构建：适用于手动构建小规模数组和复制已经有数据‘’
- 预定义形状填充：用于开始初始化固定形状的数组，如全为0占位符、全为1的数组
- 基本数字范围生成：生成数值序列，常用模拟时间序列，坐标网格等。
- 特殊矩阵生成：数学运算专用（线性代数中的单位矩阵）
- 随机数组生成：模拟实验数据
- 高级构造方法：处理非结构化数据（文件、字符串）、或者通过函数生成复杂数组

In [5]:
# 一维数组
arr = np.array([1,2,3,4])
print(arr)
print('arr的维度',arr.ndim)
print('arr的形状',arr.shape)

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('arr的维度',arr.ndim)
print('arr的形状',arr.shape)

[1 2 3 4]
arr的维度 1
arr的形状 (4,)
[[1 2 3]
 [4 5 6]]
arr的维度 2
arr的形状 (2, 3)


### nbarray的主要属性
| 属性 | 描述 | 返回类型 | 示例 |
|------|------|----------|------|
| **ndim** | 数组维度数（轴的数量） | int | `arr.ndim` |
| **shape** | 数组形状（各维度的长度） | tuple | `(3, 4)` |
| **size** | 数组中元素的总数 | int | `12` |
| **dtype** | 数组中元素的数据类型 | dtype对象 | `np.float64` |
| **itemsize** | 每个元素的字节大小 | int | `8` |
| **nbytes** | 数组总字节大小（size × itemsize） | int | `96` |
| **strides** | 内存中沿每个维度移动的字节数 | tuple | `(32, 8)` |
| **flags** | 数组内存布局的标志信息 | flags对象 | 包含C_CONTIGUOUS等 |
| **T** | 数组的转置 | ndarray | 转置后的数组 |
| **real** | 复数数组的实部 | ndarray | 实部数组 |
| **imag** | 复数数组的虚部 | ndarray | 虚部数组 |
| **flat** | 扁平迭代器，用于遍历所有元素 | flatiter对象 | 用于遍历所有元素 |
| **base** | 基础数组，如果当前数组是视图则指向原数组 | ndarray或None | 如果是视图，指向原数组 |
| **data** | 指向数组数据起始位置的缓冲区 | memoryview | 底层内存接口 |

In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('arr的维度',arr.ndim)
print('arr的形状',arr.shape)
print('arr数据类型',arr.dtype)
print('arr的size',arr.size)

[[1 2 3]
 [4 5 6]]
arr的维度 2
arr的形状 (2, 3)
arr数据类型 int64
arr的size 6


### 数据类型
| 类型名 | 字符代码 | 描述 | 字节 | 最小值 | 最大值 |
|--------|----------|------|------|--------|--------|
| int8   | i1       | 8位有符号整数 | 1 | -128 | 127 |
| int16  | i2       | 16位有符号整数 | 2 | -32768 | 32767 |
| int32  | i4       | 32位有符号整数 | 4 | -2147483648 | 2147483647 |
| int64  | i8       | 64位有符号整数 | 8 | -9.22e18 | 9.22e18 |
| uint8  | u1       | 8位无符号整数 | 1 | 0 | 255 |
| uint16 | u2       | 16位无符号整数 | 2 | 0 | 65535 |
| uint32 | u4       | 32位无符号整数 | 4 | 0 | 4294967295 |
| uint64 | u8       | 64位无符号整数 | 8 | 0 | 1.84e19 |

### 浮点数类型
| 类型名 | 字符代码 | 描述 | 字节 | 精度（小数位） | 范围 |
|--------|----------|------|------|----------------|------|
| float16 | f2 | 半精度浮点数 | 2 | ~3位 | ±65504 |
| float32 | f4 | 单精度浮点数 | 4 | ~7位 | ±3.4e38 |
| float64 | f8 | 双精度浮点数 | 8 | ~15位 | ±1.8e308 |
| float128 | f16 | 扩展精度浮点数 | 16 | ~34位 | ±1.2e4932 |

### 复数类型
| 类型名 | 字符代码 | 描述 | 字节 | 实部/虚部类型 |
|--------|----------|------|------|--------------|
| complex64 | c8 | 64位复数 | 8 | float32 |
| complex128 | c16 | 128位复数 | 16 | float64 |
| complex256 | c32 | 256位复数 | 32 | float128 |

### 其他类型
| 类型名 | 字符代码 | 描述 | 示例 |
|--------|----------|------|------|
| bool_ | ? | 布尔值 | np.bool_(True) |
| object_ | O | Python对象 | np.array([1, 'a'], dtype=object) |
| string_ | S | 字节字符串 | np.dtype('S10') |
| unicode_ | U | Unicode字符串 | np.dtype('U10') |
| datetime64 | M | 日期时间 | np.datetime64('2023-12-31') |
| timedelta64 | m | 时间间隔 | np.timedelta64(1, 'D') |